---
name: jirabp
summary: A tool to create Jira tickets from a YAML template file
description: |
  A tool to create Jira tickets from a YAML template file.
  The template can be parameterized, making it easy to
  create recurring Epics or sets of tickets. The code
  aims to be as general as possible, so it might work
  with more than one jira instance configured differently.
version: 1.0.1
base: core24
confinement: strict
license: GPL-3.0
issues: https://github.com/kewisch/jirablueprint/issues
website: https://github.com/kewisch/jirablueprint
platforms:
  amd64:
    build-on: [amd64]
  arm64:
    build-on: [arm64]

apps:
  jirabp:
    command: bin/jirabp
    environment:
      HOME: $SNAP_REAL_HOME
    plugs:
      - home
      - network

parts:
  jirabp:
    plugin: python
    source: .
